config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  resources :candidates
  resources :jobs
  resources :companies
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :user
  belongs_to :job
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :current_position, presence: true
  validates :email, presence: true
  validates :user, presence: true

  include PgSearch::Model
  multisearchable against: [:first_name, :last_name]
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :jobs
  validates :name, presence: true

  include PgSearch::Model
  multisearchable against: [:company, :name]
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :company
  has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
  # belongs_to :user
  belongs_to :company
  has_many :candidates
  validates :title, presence: true
  validates :work_type, presence: true
  validates :company, presence: true

  include PgSearch::Model
  multisearchable against: [:job, :title]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_candidate, only: %i[ show edit update destroy ]

  def index
    @results = PgSearch.multisearch(:query)
    @candidates = Candidate.all
  end

  def new
    @candidate = Candidate.new
  end

  def show; end

  def create
    @candidate = Candidate.new(candidate_params)
    @candidate.user = current_user

    if @candidate.save
      redirect_to candidates_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @candidate.update(candidate_params)
    redirect_to candidates_path(@candidate)
  end

  def destroy
    @candidate.destroy
    redirect_to candidates_path
  end

  private

  def candidate_params
    params.require(:candidate).permit(:first_name, :last_name, :current_position, :current_employer, :location, :mobile_number, :email)
  end

  def set_candidate
    @candidate = Candidate.find(params[:id])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def show; end

  private

  def company_params
    params.require(:company).permit(:job_id, :name, :location, :contact)
  end

  def set_company
    @company = Company.find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  def index
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def show; end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :mobile_number, :position, :company_id, :job_id)
  end

  def set_company
    @contact = Contact.find(params[:id])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]

  def create
    # @candidate = Candidate.find(params[:candidate_id])

    @results = PgSearch.multisearch(:query)
    @job = Job.new(job_params)
    # @job.candidate = @candidate
    # @job.user = current_user
    if @job.save
      flash[:success]= "success"
      redirect_to @job
    else
      render :new
    end
  end

  def index
    @jobs = Job.all
  end

  def new
    # @candidate = Candidate.find(params[:candidate_id])
    @job = Job.new
  end

  def show
    @candidate = @job.candidate
  end

  def update
    set_job
    @job.save!
    redirect_to job_path(@job)
  end

  def destroy
    set_job
    @job.destroy
    redirect_to root_path
  end

  private

  def job_params
    params.require(:job).permit(:candidate_id, :title, :work_type, :company, :workplace_address, :salary, :start_date)
  end

  def set_job
    @job = Job.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/candidates/edit.html.erb
<div class="container">
  <h1><%= @candidate.name %></h1>
  <%= simple_form_for @candidate do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :mobile_number %>
  <%= f.input :current_position %>
  <%= f.input :current_employer %>
  <%= f.input :location %>
  <%= link_to 'Cancel', root_path, class: 'text-danger mr-2' %>
  <%= f.submit "Confirm", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/candidates/index.html.erb
<div class="container">
  <h1>Candidates</h1>
  <% @candidates.each do |candidate| %>
  <%= link_to candidate.name, candidate_path(candidate), candidate_path(candidate), class: 'btn btn-primary' %>
  <% end %>
</div>

<%= link_to 'Add Candidate', new_candidate_path %>
<br><a href="/">Previous Page</a>

app/views/candidates/new.html.erb
<div class="container">
  <h1>Add a New Candidate</h1>
  <%= simple_form_for @candidate do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :mobile_number %>
  <%= f.input :current_position %>
  <%= f.input :current_employer %>
  <%= f.input :location %>
  <%= link_to 'Cancel', root_path, class: 'text-danger mr-2' %>
  <%= link_to 'Confirm', candidates_path, class: 'btn btn-success' %>
  <% end %>
</div>

app/views/candidates/show.html.erb
<div class="container">
  <h1><%= @candidate.first_name %></h1>
  <%= link_to 'Back', candidates_path, class: 'btn text-danger' %>
</div>

app/views/companies/index.html.erb
<div class="container">
  <h1>Companies</h1>
  <% @companies.each do |company| %>
  <%= link_to @company.name, company_path(company), class: 'btn btn-primary' %>
  <% end %>
</div>

<%= link_to 'Add Company', new_company_path %>
<br><a href="/">Previous Page</a>

app/views/companies/new.html.erb
<div class="container">
  <h1>Create New Company</h1>
  <%= simple_form_for @company do |f| %>
  <%= f.input :name, id: :company_name %>
  <%= f.input :location %>
  <%= f.input :contact %>
  <%= f.input :job_id %>
  <%= link_to 'Cancel', root_path, class: 'text-danger mr-2' %>
  <%= link_to 'Confirm', companies_path, class: 'btn btn-success' %>
  <% end %>
</div>

app/views/companies/show.html.erb
<div class="container">
  <h1><%= @company.name %></h1>
  <%= link_to 'Back', companies_path, class: 'btn text-danger' %>
</div>

app/views/contacts/index.html.erb
<div class="container">
  <h1>Contacts</h1>
  <% @contacts.each do |contact| %>
  <%= link_to contact.name, contact_path(contact), class: 'btn btn-primary' %>
  <% end %>
</div>

<%= link_to 'Add Contact', new_contact_path %>
<br><a href="/">Previous Page</a>

app/views/contacts/new.html.erb
<div class="container">
  <h1>Add a New Contact</h1>
  <%= simple_form_for @contact do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :mobile_number %>
  <%= f.input :position %>
  <%= f.input :company %>
  <%= link_to 'Cancel', root_path, class: 'text-danger mr-2' %>
  <%= link_to 'Confirm', contacts_path, class: 'btn btn-success' %>
  <% end %>
</div>

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :job_title %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company, id: :company_id %>
  </div>

  <div class="field">
    <%= form.label :work_type %>
    <%= form.text_field :work_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/index.html.erb
<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Work type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.work_type %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>
<br><a href="/">Previous Page</a>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Work type:</strong>
  <%= @job.work_type %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🔎 Talent Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render 'components/nav' %>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="homepage homepage-bg">
    <!-- The sidebar -->
    <div class="sidebar">
      <a class="active" href="#home">Home</a>
      <a <%= link_to 'Jobs', jobs_path %></a>
      <a <%= link_to 'Candidates', candidates_path %></a>
      <a <%= link_to 'Companies', companies_path %></a>
      <a <%= link_to 'Contacts', contacts_path %></a>
    </div>
</div>
<!-- Page content -->
<div>
  <h1><center>Jobs</center></h1>
    <% if @jobs.blank? %>
    <p><center>There are no jobs</center></p>
    <% else %>
    <p><center>Current Jobs:</center></p>
    <% end %>
</div>